In [3]:
import numpy as np

In [16]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
a.ndim

2

In [17]:
a.shape


(3, 2)

In [28]:
a = np.array([[1,2],[3,4],[5,6]],dtype=float)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [29]:
a.itemsize

8

In [31]:
b = np.array([[1,2],[3,4],[5,6]],dtype=complex)
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [32]:
b.itemsize

16

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
l=range(5)
l

range(0, 5)

In [39]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [41]:
print(np.char.add(['hello ','welcome '],['everyone','all']))

['hello everyone' 'welcome all']


In [45]:
print(np.char.multiply('Best ',5))

Best Best Best Best Best 


In [51]:
print(np.char.center('Best',10,fillchar='-'))

---Best---


In [52]:
print(np.char.capitalize('hello world'))

Hello world


In [53]:
print(np.char.title('hello world from python'))

Hello World From Python


In [56]:
print(np.char.lower('HELLO'))
print(np.char.lower(['HELLO','WORLD']))


hello
['hello' 'world']


In [57]:
print(np.char.upper('hello'))
print(np.char.upper(['hello','python']))


HELLO
['HELLO' 'PYTHON']


In [58]:
print(np.char.split('Python is easy and best Language'))

['Python', 'is', 'easy', 'and', 'best', 'Language']


In [59]:
print(np.char.splitlines('Hello\n What Happend Bro?'))

['Hello', ' What Happend Bro?']


In [60]:
print(np.char.strip(['apple','banana','grape'],'a')) #remove first and last letter only

['pple' 'banan' 'grape']


In [61]:
print(np.char.join([':','-'],['dmy','ymd']))

['d:m:y' 'y-m-d']


In [62]:
print(np.char.replace('He is the smart and best person','is','was'))

He was the smart and best person
